'use client';
import Link from 'next/link';
import { useState } from 'react';
const nav = ['Universities', 'Researchers', 'Publications', 'Patents', 'Analytics', 'Trust'];
const paths = [['Discover', 'Browse verified universities, public researchers, publications and patents without an account.'], ['Join', 'Register your university, prove domain ownership, then invite approved members.'], ['Contribute', 'Keep your researcher profile current and submit papers and patents with supporting evidence.'], ['Govern', 'Review submissions, manage roles, export data and keep a full audit log.']];
export default function HomePage() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  const [tab, setTab] = useState('Publications');
  const [menu, setMenu] = useState(false);
  const placeholders: Record<string, string> = { Publications: 'Search by title, author, DOI or keyword', Researchers: 'Search by name, interest or university', Universities: 'Search by name, city or country', Patents: 'Search by title, inventor or patent number' };
  return <div data-theme={theme} className="site">
    <header className="header"><div className="wrap nav"><Link className="logo" href="/"><span className="logo-mark">✓</span>VeriAcademia</Link><nav className={menu ? 'nav-links open' : 'nav-links'}>{nav.map((item) => <Link key={item} href={`/${item.toLowerCase()}`}>{item}</Link>)}</nav><div className="nav-actions"><button className="icon-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle theme">◐</button><Link className="btn signin" href="/auth/sign-in">Sign in</Link><Link className="btn primary" href="/auth/sign-up">Register</Link><button className="icon-btn menu-btn" onClick={() => setMenu(!menu)} aria-label="Open menu">☰</button></div></div></header>
    <main id="top"><section className="hero"><div className="wrap hero-grid"><div><p className="eyebrow mono">VERIFIED RESEARCH NETWORK</p><h1>Research you can trace back to a verified university.</h1><p className="lede">Search universities, researchers, publications and patents. Every record shows who verified it, when, and what you can open or request.</p><div className="search"><div className="tabs">{Object.keys(placeholders).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div><div className="search-row"><input placeholder={placeholders[tab]} aria-label="Search"/><button className="btn primary">Search</button></div></div><p className="hint">A matching email lets you apply to a university. It does not make you a member.</p><div className="chips"><span className="chip ok">✓ Verified</span><span className="chip pending">◔ Pending review</span><span className="chip request">🔒 Request required</span></div></div><div className="stage"><div className="research-card back"><span className="mono">UNIVERSITY</span><span className="chip ok">✓ Verified</span><h3>Example University</h3><p>Verified domains · 3 institutes · 12 departments</p></div><div className="research-card front"><span className="mono">doi:10.0000/sample.2026</span><span className="chip request">🔒 Request required</span><h3>Groundwater recovery in semi-arid basins</h3><p>A. Researcher, B. Scholar · Example University · 2026</p><div className="evidence"><span className="mono">EVIDENCE</span><span className="mono">Reviewed 21 Sep 2026</span><p>Affiliation confirmed by university reviewer. Revision history available.</p></div></div><div className="seal">✓</div></div></div></section>
    <section><div className="wrap"><div className="section-head"><p className="eyebrow mono">DISCOVER · JOIN · CONTRIBUTE · GOVERN</p><h2>Four ways to use VeriAcademia</h2><p>Each role sees only what it is allowed to see. Access is checked on the server, not just hidden in the menu.</p></div><div className="paths">{paths.map(([title, text], i) => <Link className="path" href={i === 0 ? '/universities' : '/auth/sign-up'} key={title}><span className="path-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></Link>)}</div></div></section>
    <section className="band"><div className="wrap split"><div><p className="eyebrow mono">THE VERIFICATION CHAIN</p><h2>How a record earns the Verified label</h2><p className="muted">Nothing is public just because it was uploaded. Each step has a named reviewer and a saved history.</p><ol className="steps"><li><b>Verify the university</b><span>Platform reviewers check evidence and domain ownership.</span></li><li><b>Approve the member</b><span>A university administrator approves each researcher.</span></li><li><b>Review the record</b><span>A reviewer checks affiliation, duplicates and rights.</span></li><li><b>Publish or protect</b><span>Protected files need an access request.</span></li></ol></div><div className="access-card"><span className="mono">ACCESS LEVELS</span><h3>Trust is visible at every step.</h3><div className="access-row"><b>Anyone</b><span>Search and read metadata</span></div><div className="access-row"><b>Registered user</b><span>Request protected access</span></div><div className="access-row"><b>Administrator</b><span>Approve, revoke, audit</span></div></div></div></section>
    <section><div className="wrap cta"><p className="eyebrow mono">BUILD THE RECORD TOGETHER</p><h2>Bring your university&apos;s research into one verified place.</h2><p>Create an account, start a university application and add your domains.</p><Link className="btn" href="/auth/sign-up">Register a university</Link></div></section></main>
    <footer><div className="wrap footer-grid"><div><div className="logo"> <span className="logo-mark">✓</span>VeriAcademia</div><p className="muted">Verified universities. Traceable research. Controlled access.</p></div><div><h4>Discover</h4>{nav.slice(0,4).map((x) => <Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</div><div><h4>Platform</h4><Link href="/trust">How verification works</Link><Link href="/analytics">Public analytics</Link><Link href="/auth/sign-up">Register a university</Link></div><div><h4>Support</h4><Link href="/help">Help</Link><Link href="/trust">Privacy</Link></div></div></footer>
  </div>;
}
